import dbConnect from "../lib/mongodb";
import Partner from "../models/partner";

const demoMerchants = [
    {
        merchantId: "demo001",
        legalName: "Demo Restaurant Pvt Ltd",
        displayName: "Tasty Bites",
        merchantSlug: "tasty-bites",
        email: "contact@tastybites.com",
        emailVerified: true,
        phone: "+91-9876543210",
        phoneVerified: true,
        password: "$2a$10$hashedpassword", // dummy hash
        category: "Restaurant",
        city: "Mumbai",
        streetAddress: "123 Food Street",
        pincode: "400001",
        locality: "Andheri",
        state: "Maharashtra",
        country: "India",
        whatsapp: "+91-9876543210",
        isWhatsappSame: true,
        gstNumber: "22AAAAA0000A1Z5",
        panNumber: "AAAAA0000A",
        businessType: "Private Limited",
        yearsInBusiness: "5",
        averageMonthlyRevenue: "500000",
        discountOffered: "10-20%",
        description: "Authentic Indian cuisine with modern twists. Serving delicious meals since 2019.",
        website: "https://tastybites.com",
        socialLinks: {
            facebook: "https://facebook.com/tastybites",
            instagram: "https://instagram.com/tastybites",
        },
        agreeToTerms: true,
        logo: "https://via.placeholder.com/200x200?text=Tasty+Bites+Logo",
        storeImages: [
            "https://via.placeholder.com/800x400?text=Store+Image+1",
            "https://via.placeholder.com/800x400?text=Store+Image+2",
        ],
        customOffer: "20% off on first order",
        ribbonTag: "Top Rated",
        mapLocation: "19.0760,72.8777",
        visibility: true,
        joinedSince: new Date("2019-01-01"),
        citywittyAssured: true,
        premiumSeller: true,
        verified: true,
        trust: true,
        topRated: true,
        ratings: [
            {
                userId: "user1",
                user: "John Doe",
                rating: 5,
                review: "Amazing food and service!",
                createdAt: new Date(),
            },
            {
                userId: "user2",
                user: "Jane Smith",
                rating: 4,
                review: "Great place, will visit again.",
                createdAt: new Date(),
            },
        ],
        averageRating: 4.5,
        tags: ["Indian", "Vegetarian", "Family Friendly"],
        status: "active",
        paymentMethodAccepted: ["Cash", "Card", "UPI"],
        qrcodeLink: "https://example.com/qr",
        businessHours: {
            open: "10:00 AM",
            close: "10:00 PM",
            days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        },
        bankDetails: {
            bankName: "HDFC Bank",
            accountHolderName: "Demo Restaurant Pvt Ltd",
            accountNumber: "1234567890",
            ifscCode: "HDFC0001234",
            upiId: "demo@upi",
        },
        ListingLimit: 100,
        Addedlistings: 50,
        totalGraphics: 10,
        totalReels: 5,
        isWebsite: true,
        totalEarnings: 250000,
        minimumOrderValue: 200,
        offlineDiscount: [
            {
                category: "Food",
                offerTitle: "Lunch Special",
                offerDescription: "20% off on lunch items",
                discountValue: 40,
                discountPercent: 20,
                status: "Active",
                validUpto: new Date("2024-12-31"),
            },
        ],
        branchLocations: [
            {
                branchName: "Main Branch",
                city: "Mumbai",
                streetAddress: "123 Food Street",
                pincode: "400001",
                locality: "Andheri",
                state: "Maharashtra",
                country: "India",
                mapLocation: "19.0760,72.8777",
                latitude: 19.0760,
                longitude: 72.8777,
            },
        ],
    },
    {
        merchantId: "demo002",
        legalName: "Fashion Hub LLC",
        displayName: "Style Central",
        merchantSlug: "style-central",
        email: "info@stylecentral.com",
        emailVerified: true,
        phone: "+91-9876543211",
        phoneVerified: true,
        password: "$2a$10$hashedpassword",
        category: "Fashion",
        city: "Delhi",
        streetAddress: "456 Fashion Avenue",
        pincode: "110001",
        locality: "Connaught Place",
        state: "Delhi",
        country: "India",
        whatsapp: "+91-9876543211",
        isWhatsappSame: true,
        gstNumber: "07AAAAA0000A1Z5",
        panNumber: "AAAAA0000B",
        businessType: "LLC",
        yearsInBusiness: "3",
        averageMonthlyRevenue: "300000",
        discountOffered: "15-25%",
        description: "Trendy fashion for all ages. Latest collections from top brands.",
        website: "https://stylecentral.com",
        socialLinks: {
            instagram: "https://instagram.com/stylecentral",
        },
        agreeToTerms: true,
        logo: "https://via.placeholder.com/200x200?text=Style+Central+Logo",
        storeImages: [
            "https://via.placeholder.com/800x400?text=Store+Image+1",
        ],
        customOffer: "Buy 1 Get 1 Free on selected items",
        ribbonTag: "New Arrival",
        mapLocation: "28.6139,77.2090",
        visibility: true,
        joinedSince: new Date("2021-01-01"),
        citywittyAssured: false,
        ratings: [
            {
                userId: "user3",
                user: "Alice Johnson",
                rating: 4,
                review: "Good variety of clothes.",
                createdAt: new Date(),
            },
        ],
        averageRating: 4.0,
        tags: ["Fashion", "Clothing", "Accessories"],
        status: "active",
        paymentMethodAccepted: ["Card", "UPI"],
        businessHours: {
            open: "11:00 AM",
            close: "9:00 PM",
            days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        },
        bankDetails: {
            bankName: "ICICI Bank",
            accountHolderName: "Fashion Hub LLC",
            accountNumber: "1234567891",
            ifscCode: "ICIC0001234",
            upiId: "fashion@upi",
        },
        ListingLimit: 200,
        Addedlistings: 80,
        totalGraphics: 15,
        totalReels: 8,
        isWebsite: false,
        totalEarnings: 150000,
        minimumOrderValue: 500,
        offlineDiscount: [
            {
                category: "Clothing",
                offerTitle: "Winter Sale",
                offerDescription: "25% off on winter collection",
                discountValue: 125,
                discountPercent: 25,
                status: "Active",
                validUpto: new Date("2024-02-28"),
            },
        ],
        branchLocations: [
            {
                branchName: "Delhi Branch",
                city: "Delhi",
                streetAddress: "456 Fashion Avenue",
                pincode: "110001",
                locality: "Connaught Place",
                state: "Delhi",
                country: "India",
                mapLocation: "28.6139,77.2090",
                latitude: 28.6139,
                longitude: 77.2090,
            },
        ],
    },
    {
        merchantId: "demo003",
        legalName: "Tech Solutions Inc",
        displayName: "Gadget World",
        merchantSlug: "gadget-world",
        email: "support@gadgetworld.com",
        emailVerified: true,
        phone: "+91-9876543212",
        phoneVerified: true,
        password: "$2a$10$hashedpassword",
        category: "Electronics",
        city: "Bangalore",
        streetAddress: "789 Tech Park",
        pincode: "560001",
        locality: "Whitefield",
        state: "Karnataka",
        country: "India",
        whatsapp: "+91-9876543212",
        isWhatsappSame: true,
        gstNumber: "29AAAAA0000A1Z5",
        panNumber: "AAAAA0000C",
        businessType: "Incorporated",
        yearsInBusiness: "7",
        averageMonthlyRevenue: "800000",
        discountOffered: "5-15%",
        description: "Latest gadgets and electronics at competitive prices.",
        website: "https://gadgetworld.com",
        socialLinks: {
            youtube: "https://youtube.com/gadgetworld",
        },
        agreeToTerms: true,
        logo: "https://via.placeholder.com/200x200?text=Gadget+World+Logo",
        storeImages: [
            "https://via.placeholder.com/800x400?text=Store+Image+1",
            "https://via.placeholder.com/800x400?text=Store+Image+2",
            "https://via.placeholder.com/800x400?text=Store+Image+3",
        ],
        customOffer: "Free delivery on orders above ₹1000",
        ribbonTag: "Best Seller",
        mapLocation: "12.9716,77.5946",
        visibility: true,
        joinedSince: new Date("2017-01-01"),
        citywittyAssured: true,
        ratings: [
            {
                userId: "user4",
                user: "Bob Wilson",
                rating: 5,
                review: "Excellent service and quality products.",
                createdAt: new Date(),
            },
            {
                userId: "user5",
                user: "Charlie Brown",
                rating: 3,
                review: "Good but delivery was delayed.",
                createdAt: new Date(),
            },
        ],
        averageRating: 4.0,
        tags: ["Electronics", "Gadgets", "Tech"],
        status: "active",
        paymentMethodAccepted: ["Cash", "Card", "UPI", "Net Banking"],
        businessHours: {
            open: "10:00 AM",
            close: "8:00 PM",
            days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        },
        bankDetails: {
            bankName: "SBI",
            accountHolderName: "Tech Solutions Inc",
            accountNumber: "1234567892",
            ifscCode: "SBIN0001234",
            upiId: "tech@upi",
        },
        ListingLimit: 300,
        Addedlistings: 150,
        totalGraphics: 20,
        totalReels: 12,
        isWebsite: true,
        totalEarnings: 400000,
        minimumOrderValue: 100,
        offlineDiscount: [
            {
                category: "Electronics",
                offerTitle: "Festive Sale",
                offerDescription: "15% off on all electronics",
                discountValue: 150,
                discountPercent: 15,
                status: "Active",
                validUpto: new Date("2024-12-31"),
            },
        ],
        branchLocations: [
            {
                branchName: "Bangalore HQ",
                city: "Bangalore",
                streetAddress: "789 Tech Park",
                pincode: "560001",
                locality: "Whitefield",
                state: "Karnataka",
                country: "India",
                mapLocation: "12.9716,77.5946",
                latitude: 12.9716,
                longitude: 77.5946,
            },
        ],
    },
    {
        merchantId: "demo004",
        legalName: "Beauty Essentials Ltd",
        displayName: "Glow Up Beauty",
        merchantSlug: "glow-up-beauty",
        email: "hello@glowupbeauty.com",
        emailVerified: true,
        phone: "+91-9876543213",
        phoneVerified: true,
        password: "$2a$10$hashedpassword",
        category: "Beauty",
        city: "Chennai",
        streetAddress: "321 Beauty Lane",
        pincode: "600001",
        locality: "T. Nagar",
        state: "Tamil Nadu",
        country: "India",
        whatsapp: "+91-9876543213",
        isWhatsappSame: true,
        gstNumber: "33AAAAA0000A1Z5",
        panNumber: "AAAAA0000D",
        businessType: "Limited",
        yearsInBusiness: "4",
        averageMonthlyRevenue: "250000",
        discountOffered: "10-30%",
        description: "Premium beauty products for all skin types.",
        website: "https://glowupbeauty.com",
        socialLinks: {
            instagram: "https://instagram.com/glowupbeauty",
            facebook: "https://facebook.com/glowupbeauty",
        },
        agreeToTerms: true,
        logo: "https://via.placeholder.com/200x200?text=Glow+Up+Beauty+Logo",
        storeImages: [
            "https://via.placeholder.com/800x400?text=Store+Image+1",
        ],
        customOffer: "Free makeup consultation",
        ribbonTag: "Trending",
        mapLocation: "13.0827,80.2707",
        visibility: true,
        joinedSince: new Date("2020-01-01"),
        citywittyAssured: false,
        ratings: [
            {
                userId: "user6",
                user: "Diana Prince",
                rating: 5,
                review: "Amazing products and staff!",
                createdAt: new Date(),
            },
        ],
        averageRating: 5.0,
        tags: ["Beauty", "Skincare", "Makeup"],
        status: "active",
        paymentMethodAccepted: ["Card", "UPI"],
        businessHours: {
            open: "9:00 AM",
            close: "7:00 PM",
            days: ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        },
        bankDetails: {
            bankName: "Axis Bank",
            accountHolderName: "Beauty Essentials Ltd",
            accountNumber: "1234567893",
            ifscCode: "UTIB0001234",
            upiId: "beauty@upi",
        },
        ListingLimit: 150,
        Addedlistings: 70,
        totalGraphics: 8,
        totalReels: 4,
        isWebsite: true,
        totalEarnings: 125000,
        minimumOrderValue: 300,
        offlineDiscount: [
            {
                category: "Beauty",
                offerTitle: "Skin Care Special",
                offerDescription: "30% off on skincare products",
                discountValue: 90,
                discountPercent: 30,
                status: "Active",
                validUpto: new Date("2024-06-30"),
            },
        ],
        branchLocations: [
            {
                branchName: "Chennai Store",
                city: "Chennai",
                streetAddress: "321 Beauty Lane",
                pincode: "600001",
                locality: "T. Nagar",
                state: "Tamil Nadu",
                country: "India",
                mapLocation: "13.0827,80.2707",
                latitude: 13.0827,
                longitude: 80.2707,
            },
        ],
    },
];

async function seedMerchants() {
    try {
        await dbConnect();
        console.log("Connected to database");

        // Clear existing demo merchants
        await Partner.deleteMany({ merchantId: { $regex: /^demo/ } });
        console.log("Cleared existing demo merchants");

        // Insert new demo merchants
        const inserted = await Partner.insertMany(demoMerchants);
        console.log(`Inserted ${inserted.length} demo merchants`);

        console.log("Seeding completed successfully");
    } catch (error) {
        console.error("Error seeding merchants:", error);
    } finally {
        process.exit(0);
    }
}

seedMerchants();
